GMname = {
'Observatory': (1,'Observatoire'),
'Temple of Relics': (2,'Temple des Reliques'),
'Oracle of Delphi': (3,'Oracle de delphes'),
'Gaea Statue': (4,'Statue de Gaia'),
'Arctic Orangery': (5,'Orangerie arctique'),
'Seed Vault': (6,'Chambre forte des graines'),
'Tower of Babel': (7,'Tour de Babel'),
'Statue of Zeus': (8,'Statue de Zeus'),
'Frauenkirche of Dresden': (9,'Frauenkirche de Dresde'),
'Deal Castle': (10,'Chateau de Deal'),
'Lotus Temple': (11,'Temple du lotus'),
'Innovation Tower': (12,'Tour d\'innovation'),
'Hagia Sophia': (13,'Hagia sophia'),
'Cathedral of Aachen': (14,"Cathédrale d'Aix-la-Chapelle"),
'Galata Tower': (15,'Tour de Galata'),
'The Arc': (16,'L\'Arche'),
'Rain Forest Project': (17,"Forêt tropicale"),
"St. Mark's Basilica": (18,'Basilique Saint-Marc'),
'Notre Dame': (19,'Notre-Dame'),
'Royal Albert Hall': (20,"Royal Albert Hall"),
'Capitol': (21,'Capitole'),
'Koloseum': (22,"Colisée"),
'Lighthouse of Alexandria': (23,'Phare d\'Alexandrie'),
'Saint Basils Cathedral': (24,'Cathédrale Saint-Basile'),
'Castel del Monte': (25,'Castel del Monte'),
'Space Needle': (26,'Space Needle'),
'Atomium': (27,'Atomium'),
'Atlantis Museum': (28,'Musée d\'Atlantide'),
'The Kraken': (29,'Le Kraken'),
'The Blue Galaxy': (30,'La Galaxie Bleue'),
'Cape Canaveral': (31,'Cape Canaveral'),
'The Habitat': (32,'L\'Habitat'),
'Alcatraz': (33,'Alcatraz'),
'Château Frontenac': (34,'Château Frontenac'),
'Space Carrier': (35,'Transporteur spatial'),
'Star Gazer': (36,"Star Gazer"),
'The Virgo Project': (37,'Le projet Virgo'),
'Flying Island': (38,'Île volante'),
'Voyager V1': (39,'Voyager V1'),
'Truce Tower': (40,"Tour de la trêve"),
'Terracotta Army': (41,'Armée de terre cuite'),
'Himeji Castle': (42, 'Château de Himeji'),
}

GM_ID = {
'Observatory': 'X_AllAge_EasterBonus4',
'Temple of Relics': 'X_AllAge_Expedition',
'Oracle of Delphi': 'X_AllAge_Oracle',
'Gaea Statue': 'X_ArcticFuture_Landmark1',
'Arctic Orangery': 'X_ArcticFuture_Landmark2',
'Seed Vault': 'X_ArcticFuture_Landmark3',
'Tower of Babel': 'X_BronzeAge_Landmark1',
'Statue of Zeus': 'X_BronzeAge_Landmark2',
'Frauenkirche of Dresden': 'X_ColonialAge_Landmark1',     
'Deal Castle': 'X_ColonialAge_Landmark2',
'Lotus Temple': 'X_ContemporaryEra_Landmark1',
'Innovation Tower': 'X_ContemporaryEra_Landmark2',        
'Hagia Sophia': 'X_EarlyMiddleAge_Landmark1',
'Cathedral of Aachen': 'X_EarlyMiddleAge_Landmark2',      
'Galata Tower': 'X_EarlyMiddleAge_Landmark3',
'The Arc': 'X_FutureEra_Landmark1',
'Rain Forest Project': 'X_FutureEra_Landmark2',
'St. Mark\'s Basilica': 'X_HighMiddleAge_Landmark1',       
'Notre Dame': 'X_HighMiddleAge_Landmark3',
'Royal Albert Hall': 'X_IndustrialAge_Landmark1',
'Capitol': 'X_IndustrialAge_Landmark2',
'Koloseum': 'X_IronAge_Landmark1',
'Lighthouse of Alexandria': 'X_IronAge_Landmark2',        
'Saint Basils Cathedral': 'X_LateMiddleAge_Landmark1',    
'Castel del Monte': 'X_LateMiddleAge_Landmark3',
'Space Needle': 'X_ModernEra_Landmark1',
'Atomium': 'X_ModernEra_Landmark2',
'Atlantis Museum': 'X_OceanicFuture_Landmark1',
'The Kraken': 'X_OceanicFuture_Landmark2',
'The Blue Galaxy': 'X_OceanicFuture_Landmark3',
'Cape Canaveral': 'X_PostModernEra_Landmark1',
'The Habitat': 'X_PostModernEra_Landmark2',
'Alcatraz': 'X_ProgressiveEra_Landmark1',
'Château Frontenac': 'X_ProgressiveEra_Landmark2',        
'Space Carrier': 'X_SpaceAgeAsteroidBelt_Landmark1',      
'Star Gazer': 'X_SpaceAgeMars_Landmark1',
'The Virgo Project': 'X_SpaceAgeMars_Landmark2',
'Flying Island': 'X_SpaceAgeVenus_Landmark1',
'Voyager V1': 'X_TomorrowEra_Landmark1',
'Truce Tower': 'X_TomorrowEra_Landmark2',
'Terracotta Army': 'X_VirtualFuture_Landmark1',
'Himeji Castle': 'X_VirtualFuture_Landmark2'
}