GMname = {
'Observatory': 'Observatoire',
'Temple of Relics': 'Temple des Reliques',
'Oracle of Delphi': 'Oracle de delphes',
'Gaea Statue': 'Statue de Gaia',
'Arctic Orangery': 'Orangerie arctique',
'Seed Vault': 'Chambre forte des graines',
'Tower of Babel': 'Tour de Babel',
'Statue of Zeus': 'Statue de Zeus',
'Frauenkirche of Dresden': 'Frauenkirche de Dresde',
'Deal Castle': 'Chateau de Deal',
'Lotus Temple': 'Temple du lotus',
'Innovation Tower': 'Tour d\'innovation',
'Hagia Sophia': 'Hagia sophia',
'Cathedral of Aachen': "Cathédrale d'Aix-la-Chapelle",
'Galata Tower': 'Tour de Galata',
'The Arc': 'L\'Arche',
'Rain Forest Project': "Forêt tropicale",
"St. Mark's Basilica": 'Basilique Saint-Marc',
'Notre Dame': 'Notre-Dame',
'Royal Albert Hall': "Royal Albert Hall",
'Capitol': 'Capitole',
'Koloseum': "Colisée",
'Lighthouse of Alexandria': 'Phare d\'Alexandrie',
'Saint Basils Cathedral': 'Cathédrale Saint-Basile',
'Castel del Monte': 'Castel del Monte',
'Space Needle': 'Space Needle',
'Atomium': 'Atomium',
'Atlantis Museum': 'Musée d\'Atlantide',
'The Kraken': 'Le Kraken',
'The Blue Galaxy': 'La Galaxie Bleue',
'Cape Canaveral': 'Cape Canaveral',
'The Habitat': 'L\'Habitat',
'Alcatraz': 'Alcatraz',
'Château Frontenac': 'Château Frontenac',
'Space Carrier': 'Transporteur spatial',
'Star Gazer': "	Star Gazer",
'The Virgo Project': 'Le projet Virgo',
'Flying Island': 'Île volante',
'Voyager V1': 'Voyager V1',
'Truce Tower': "Tour de la trêve",
'Terracotta Army': 'Armée de terre cuite',
'Himeji Castle': 'Château de Himeji',
}

GM_ID = {
'Observatory': 'X_AllAge_EasterBonus4',
'Temple of Relics': 'X_AllAge_Expedition',
'Oracle of Delphi': 'X_AllAge_Oracle',
'Gaea Statue': 'X_ArcticFuture_Landmark1',
'Arctic Orangery': 'X_ArcticFuture_Landmark2',
'Seed Vault': 'X_ArcticFuture_Landmark3',
'Tower of Babel': 'X_BronzeAge_Landmark1',
'Statue of Zeus': 'X_BronzeAge_Landmark2',
'Frauenkirche of Dresden': 'X_ColonialAge_Landmark1',     
'Deal Castle': 'X_ColonialAge_Landmark2',
'Lotus Temple': 'X_ContemporaryEra_Landmark1',
'Innovation Tower': 'X_ContemporaryEra_Landmark2',        
'Hagia Sophia': 'X_EarlyMiddleAge_Landmark1',
'Cathedral of Aachen': 'X_EarlyMiddleAge_Landmark2',      
'Galata Tower': 'X_EarlyMiddleAge_Landmark3',
'The Arc': 'X_FutureEra_Landmark1',
'Rain Forest Project': 'X_FutureEra_Landmark2',
'St. Mark\'s Basilica': 'X_HighMiddleAge_Landmark1',       
'Notre Dame': 'X_HighMiddleAge_Landmark3',
'Royal Albert Hall': 'X_IndustrialAge_Landmark1',
'Capitol': 'X_IndustrialAge_Landmark2',
'Koloseum': 'X_IronAge_Landmark1',
'Lighthouse of Alexandria': 'X_IronAge_Landmark2',        
'Saint Basils Cathedral': 'X_LateMiddleAge_Landmark1',    
'Castel del Monte': 'X_LateMiddleAge_Landmark3',
'Space Needle': 'X_ModernEra_Landmark1',
'Atomium': 'X_ModernEra_Landmark2',
'Atlantis Museum': 'X_OceanicFuture_Landmark1',
'The Kraken': 'X_OceanicFuture_Landmark2',
'The Blue Galaxy': 'X_OceanicFuture_Landmark3',
'Cape Canaveral': 'X_PostModernEra_Landmark1',
'The Habitat': 'X_PostModernEra_Landmark2',
'Alcatraz': 'X_ProgressiveEra_Landmark1',
'Château Frontenac': 'X_ProgressiveEra_Landmark2',        
'Space Carrier': 'X_SpaceAgeAsteroidBelt_Landmark1',      
'Star Gazer': 'X_SpaceAgeMars_Landmark1',
'The Virgo Project': 'X_SpaceAgeMars_Landmark2',
'Flying Island': 'X_SpaceAgeVenus_Landmark1',
'Voyager V1': 'X_TomorrowEra_Landmark1',
'Truce Tower': 'X_TomorrowEra_Landmark2',
'Terracotta Army': 'X_VirtualFuture_Landmark1',
'Himeji Castle': 'X_VirtualFuture_Landmark2'
}